import { SPMIData } from '../types';
import { LANDASAN_HUKUM } from '../constants';

export function generateLocalDocumentContent(templateId: string, data: SPMIData): string {
  const dateStr = "21 Juli 2026";
  const header = `=== DOKUMEN SISTEM PENJAMINAN MUTU INTERNAL ===\n\nNAMA INSTITUSI : ${data.namaSekolah.toUpperCase()}\nYAYASAN        : ${data.yayasan.toUpperCase()}\nALAMAT         : ${data.alamat}\nNOMOR DOKUMEN  : SPMI-AG/2026/SKL/VOL-I\nREVISI         : 01 (Penyesuaian Standar Kompetensi Lulusan)\nTANGGAL BERLAKU: ${dateStr}\n\n`;
  const footer = `\n\n--------------------------------------------------\nDitetapkan di  : Purwokerto / Gunung Sindur\nPada Tanggal   : ${dateStr}\n\nMengetahui,\nKepala Sekolah ${data.namaSekolah}\n\n\n\n${data.kepalaSekolah}\nNIP. 198504122010011005`;

  const commonIntro = `Penyelenggaraan Sistem Penjaminan Mutu Internal (SPMI) di SMA Islam Al Ghozali merupakan perwujudan nyata komitmen kami untuk menghadirkan layanan pendidikan bermutu tinggi yang relevan dengan tuntutan zaman. Melalui pendekatan Perencanaan Berbasis Data (PBD) dan mengacu pada Rapor Pendidikan Kemendikbudristek, kami merumuskan strategi penjaminan mutu yang terarah, dinamis, dan berkelanjutan. Fokus kami adalah mengintegrasikan aspek akademik nasional dengan pembiasaan keagamaan khas pesantren (Syari’ah, Kauniyah, dan Nafi’ah) guna melahirkan lulusan yang bertakwa, cerdas, dan berdaya saing global.`;

  switch (templateId) {
    case "SK Tim":
      return `${header}SURAT KEPUTUSAN KEPALA SMA ISLAM AL-GHOZALI\nNomor: 042/SK-SPMI/SMA-AG/I/2026\n\nTENTANG\nPENETAPAN TIM PENJAMINAN MUTU INTERNAL (TPMPS)\nTAHUN AJARAN 2026/2027\n\nMEMUTUSKAN:\n\nMenetapkan Struktur Organisasi dan Personalia Tim Penjaminan Mutu Pendidikan Sekolah (TPMPS) SMA Islam Al Ghozali Tahun 2026 sebagai berikut:\n\n[TABLE_START]\n[TABLE_ROW]No|Jabatan Tim Mutu|Nama / NIP|Rincian Tugas & Tanggung Jawab\n[TABLE_ROW]1|Penanggung Jawab|${data.kepalaSekolah}|Bertanggung jawab penuh atas seluruh kebijakan, pelaksanaan, dan laporan SPMI sekolah.\n[TABLE_ROW]2|Ketua TPMPS|${data.ketuaSPMI} (Waka Kurikulum)|Mengoordinasikan pelaksanaan siklus PPEPP dan sinkronisasi Perencanaan Berbasis Data (PBD).\n[TABLE_ROW]3|Sekretaris|Staf Administrasi Mutu|Mengelola seluruh arsip, penyusunan instrumen evaluasi, dan rekapitulasi data SPMI.\n[TABLE_ROW]4|PJ Standar Lulusan & Isi|Koordinator Kurikulum|Pemetaan capaian literasi-numerasi serta penyelarasan Alur Tujuan Pembelajaran (ATP).\n[TABLE_ROW]5|PJ Standar Proses & Evaluasi|Koordinator Pembelajaran|Supervisi KBM, pemanfaatan AI/teknologi pembelajaran, dan klinik remedial.\n[TABLE_ROW]6|PJ Sarpras & Pembiayaan|Wakil Kepala Sekolah Sarpras|Penyediaan laboratorium digital, perbaikan fasilitas fisik, dan transparansi budget RKAS.\n[TABLE_END]\n\nKetentuan SK: SK ini berlaku sejak tanggal ditetapkan hingga 31 Desember 2026. Apabila terdapat kekeliruan di kemudian hari, akan diadakan perbaikan sebagaimana mestinya.\n\n${commonIntro}\n\nTPMPS bertanggung jawab penuh atas kelancaran siklus PPEPP (Penetapan, Pelaksanaan, Evaluasi, Pengendalian, dan Peningkatan) di tingkat sekolah.${footer}`;

    case "Manual SPMI":
      return `${header}MANUAL SISTEM PENJAMINAN MUTU INTERNAL (SPMI)\n\nBAB I: PENDAHULUAN\n\n${commonIntro}\n\nManual ini dirancang sebagai panduan praktis bagi TPMPS dalam menjalankan seluruh proses penjaminan mutu secara sirkuler dan berkelanjutan. Penjaminan mutu bukanlah program sesaat, melainkan budaya kerja harian yang menuntut kolaborasi aktif, integrasi teknologi, dan evaluasi berbasis fakta keras (hard data).\n\nBAB II: LANDASAN YURIDIS\n\n${LANDASAN_HUKUM}\n\nBAB III: VISI DAN MISI MUTU\n\nVISI MUTU:\n"${data.visi}"\n\nMISI MUTU:\n${data.misi}\n\nBAB IV: KERANGKA STANDAR KOMPETENSI LULUSAN (SKL) KHAS AL-GHOZALI\n\nStandar Kompetensi Lulusan dikelompokkan ke dalam tiga domain utama yang terintegrasi secara holistik:\n\n[TABLE_START]\n[TABLE_ROW]Domain SKL|Indikator Kelulusan Nasional|Integrasi Kekhasan Al-Ghozali\n[TABLE_ROW]1. Sikap & Karakter (Affective)|Beriman, bertakwa kepada Tuhan YME, berakhlak mulia, bergotong royong, mandiri, bernalar kritis, dan berkebinekaan global.|Kedisiplinan ibadah harian, penguasaan adab santri, kebiasaan zikir/doa, serta menjunjung tinggi kepedulian sosial.\n[TABLE_ROW]2. Pengetahuan (Cognitive)|Penguasaan konsep keilmuan mutakhir, literasi numerasi, metodologi penelitian ilmiah tingkat menengah, serta kesiapan ujian akademik (TKA/SNBT).|Penguasaan dasar-dasar ilmu syariah, pemahaman literatur keislaman, serta integrasi nilai sains dan agama.\n[TABLE_ROW]3. Keterampilan (Psychomotor)|Keterampilan berpikir tingkat tinggi (HOTS), komunikasi publik, penyusunan Karya Tulis Ilmiah (KTI), serta pemanfaatan teknologi digital secara bijak.|Kemampuan orasi ilmiah/public speaking (khutbah/mudarabah), bahasa asing (Arab/Inggris), serta kemandirian kepemimpinan.\n[TABLE_END]\n\nBAB V: SIKLUS PPEPP\n\n1. Penetapan (P): Menetapkan target pencapaian SKL melalui musyawarah kerja TPMPS.\n2. Pelaksanaan (P): Menyelenggarakan program pembelajaran berbasis IT, pembiasaan karakter Islami, dan klinik numerasi.\n3. Evaluasi (E): Melakukan EDS, Monev berkala, dan analisis hasil ujian sumatif.\n4. Pengendalian (P): Merumuskan tindakan korektif jika terjadi kesenjangan (gap) capaian.\n5. Peningkatan (P): Meningkatkan standar kompetensi pada siklus berikutnya (Continuous Quality Improvement).${footer}`;

    case "Kebijakan Mutu":
      return `${header}DOKUMEN KEBIJAKAN MUTU SPMI\n\n1. PENDAHULUAN & LATAR BELAKANG\n\n${commonIntro}\n\nPeningkatan mutu pendidikan merupakan pilar fundamental dalam mewujudkan tujuan pendidikan nasional. Di era transformasi digital dan disrupsi global, mutu satuan pendidikan tidak lagi diukur secara parsial melainkan secara komprehensif melalui derajat kesesuaian antara layanan nyata sekolah dengan Standar Nasional Pendidikan (SNP).\n\n2. ASAS DAN PRINSIP KEBIJAKAN MUTU\n\nKebijakan mutu SMA Islam Al Ghozali mengacu pada lima komitmen utama:\n- Menjamin dan menjaga mutu dalam seluruh aspek akademik, non-akademik, dan tata kelola.\n- Menyelenggarakan proses pembelajaran yang integratif antara ilmu umum dan kepesantrenan.\n- Meningkatkan kompetensi pendidik secara berkelanjutan dalam pemanfaatan teknologi kecerdasan buatan (AI) dan platform digital.\n- Mewujudkan transparansi, akuntabilitas publik, dan komunikasi terbuka dengan komite serta orang tua murid.\n- Melakukan evaluasi berkala secara mandiri, jujur, dan berorientasi pada data nyata (Rapor Pendidikan).\n\n3. RUANG LINGKUP\n\nKebijakan mutu ini mencakup pengelolaan kurikulum operasional, pembinaan karakter (habituasi siswa), pelatihan guru, modernisasi sarana prasarana digital, serta pengelolaan keuangan sekolah yang transparan dan akuntabel.\n\n4. IMPLEMENTASI DAN TANGGUNG JAWAB\n\nSeluruh civitas akademika wajib memahami, melaksanakan, dan mendukung pencapaian standar mutu yang ditetapkan oleh TPMPS. Keberhasilan pelaksanaan kebijakan ini diukur dari tumbuhnya budaya mutu mandiri di lingkungan sekolah.${footer}`;

    case "Standar Mutu":
      return `${header}MATRIKS STANDAR KOMPETENSI LULUSAN (SKL) INDIKATOR UTAMA\n\nAspek Standar Kompetensi Lulusan (SKL) di sekolah kami dirancang khusus secara komprehensif, mengintegrasikan kurikulum nasional dengan kekhasan moral keagamaan pesantren. Seluruh guru wajib menggunakan indikator di bawah ini sebagai basis penilaian harian dan evaluasi kelulusan.\n\nI. BIDANG SYARI’AH\n\n[TABLE_START]\n[TABLE_ROW]No|Indikator Kompetensi|Status|Catatan (Hafalan/Pemahaman)\n[TABLE_ROW]1|Mampu membaca Al-Qur’an dengan fasih|Aktif|Sesuai tajwid dan makharijul huruf\n[TABLE_ROW]2|Menguasai ilmu tajwid secara mendalam|Aktif|Hukum nun mati, mim mati, mad, dll.\n[TABLE_ROW]3|Memahami Fiqih Mu’amalah|Aktif|Tata cara transaksi sosial syariah\n[TABLE_ROW]4|Hafalan 5 Juz (Juz 27, 28, 29, 30, dan 1)|Dalam Proses|Setoran terjadwal secara periodik\n[TABLE_END]\n\nII. BIDANG KAUNIYAH\n\n[TABLE_START]\n[TABLE_ROW]No|Indikator Kompetensi|Status|Catatan (Nilai/Karya)\n[TABLE_ROW]1|Mampu membuat Karya Tulis Ilmiah (KTI)|Aktif|Penyusunan KTI mandiri kelas XII\n[TABLE_ROW]2|Menguasai kemampuan numerik dan kalkulus|Aktif|Logika matematika & aljabar dasar\n[TABLE_ROW]3|Berpidato & menulis teks dalam Bahasa Arab|Aktif|Kemampuan Muhadharah / khutbah\n[TABLE_ROW]4|Berpidato & menulis teks dalam Bahasa Inggris|Aktif|Kemampuan pidato & menulis esai\n[TABLE_ROW]5|Mencapai KKM & kesiapan Ujian Masuk PTN|Aktif|Persentase tryout SNBT di atas KKM\n[TABLE_END]\n\nIII. BIDANG NAFI’AH\n\n[TABLE_START]\n[TABLE_ROW]No|Indikator Kompetensi|Status|Keterangan\n[TABLE_ROW]1|Memiliki kemampuan berorganisasi yang baik|Aktif|Kepengurusan OSIS & Pramuka\n[TABLE_ROW]2|Menguasai keterampilan masa depan (Hard Skill)|Aktif|Literasi IT & keahlian digital praktis\n[TABLE_ROW]3|Menguasai keterampilan masa depan (Soft Skill)|Aktif|Problem solving, kolaborasi, & komunikasi\n[TABLE_END]\n\nStandar Mutu Lulusan di atas merupakan modalitas dasar dalam menjamin lulusan yang berdaya saing tinggi dan berakhlakul karimah.${footer}`;

    case "Evaluasi Diri Sekolah":
      return `${header}DOKUMEN EVALUASI DIRI SEKOLAH (EDS)\n\n1. PROFIL DAN METODE EVALUASI\n\nEvaluasi Diri Sekolah dilaksanakan secara partisipatif dengan melibatkan seluruh pemangku kepentingan (TPMPS, dewan guru, komite, dan perwakilan siswa). EDS disusun berdasarkan delapan Standar Nasional Pendidikan (SNP) dengan memetakan kekuatan (strengths), kelemahan (weaknesses), peluang (opportunities), dan ancaman (threats).\n\n2. ANALISIS KONDISI RIIL (8 SNP)\n\n- Standar Kompetensi Lulusan: Karakter spiritual siswa sangat kuat, namun kesiapan ujian SNBT masih perlu peningkatan (numerasi sedang).\n- Standar Isi & Proses: Kurikulum kepesantrenan telah terintegrasi dengan baik, namun metode pengajaran interaktif berbasis teknologi belum merata.\n- Standar Pendidik & Tenaga Kependidikan: Seluruh guru berpendidikan S1/S2, namun penguasaan teknologi informasi dan pembuatan modul pembelajaran mandiri (LMS) masih perlu pendampingan.\n- Standar Sarana Prasarana: Laboratorium komputer memadai, namun ketersediaan smart board dan konektivitas internet perlu ditingkatkan.\n\n3. ANALISIS SWOT DAN REKOMENDASI\n\n- Strength (Kekuatan): Dukungan penuh dari yayasan, lingkungan belajar yang kondusif (aman dari perundungan), dan keunikan kurikulum khas.\n- Weakness (Kelemahan): Rendahnya literasi digital guru, dan nilai rata-rata numerasi siswa sedang (64.20).\n- Opportunity (Peluang): Kemitraan dengan dunia industri (DU/DI) dan komunitas belajar eksternal.\n- Threat (Ancaman): Perubahan regulasi kurikulum nasional dan tuntutan kompetensi teknologi yang dinamis.\n\nREKOMENDASI:\n- Melaksanakan pelatihan pembuatan bahan ajar digital (modul AI) secara berkala bagi seluruh guru.\n- Membuka klinik numerasi terstruktur mingguan untuk mendongkrak tryout UTBK siswa.${footer}`;

    case "Peta Mutu":
      return `${header}PETA MUTU PENDIDIKAN DAN ANALISIS GAP\n\nPeta mutu dilakukan berdasarkan indikator prioritas Rapor Pendidikan Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi:\n\n[TABLE_START]\n[TABLE_ROW]Indikator Prioritas Mutu|Capaian Saat Ini|Status Mutu|Analisis & Target 2026\n[TABLE_ROW]A.1 Kemampuan Literasi|78.50 %|Tinggi|Pertahankan dan tingkatkan kemampuan analisis teks ilmiah.\n[TABLE_ROW]A.2 Kemampuan Numerasi|64.20 %|Sedang|Fokus perbaikan: Penguatan penalaran matematika & statistik dasar.\n[TABLE_ROW]A.3 Indeks Karakter|82.10 %|Sangat Baik|Karakter Islami, Kemandirian, dan Gotong Royong tertanam kuat.\n[TABLE_ROW]D.1 Kualitas Pembelajaran|71.80 %|Baik|Perlu peningkatan metode interaktif & integrasi ICT/AI pembelajaran.\n[TABLE_ROW]D.4 Iklim Keamanan Sekolah|88.40 %|Aman|Bebas dari perundungan, kekerasan fisik, dan intoleransi.\n[TABLE_ROW]D.8 Iklim Kebinekaan|85.00 %|Sangat Baik|Toleransi dan budaya inklusif terimplementasi secara konsisten.\n[TABLE_END]\n\nAKAR MASALAH UTAMA:\nKemampuan numerasi siswa berada pada predikat "Sedang" (64.20) karena integrasi latihan berbasis HOTS pada mata pelajaran eksak belum merata di semua tingkatan kelas. Selain itu, guru memerlukan pelatihan peningkatan kompetensi dalam mengelola metode pembelajaran aktif dan interaktif berbasis ICT.\n\nREKOMENDASI PEMETAAN PRIORITAS:\n1. Mengoptimalkan komunitas belajar guru (Kombel) setiap hari Jumat sore.\n2. Pembiasaan 15 menit membaca literasi ilmiah Islami dan penyelesaian 2 soal numerasi HOTS setiap pagi sebelum KBM dimulai.${footer}`;

    case "Analisis Rapor Pendidikan":
      return `${header}ANALISIS RAPOR PENDIDIKAN\n\nI. HASIL ANALISIS INDIKATOR UTAMA\n\nBerdasarkan data Rapor Pendidikan tahun ajaran terakhir, profil mutu SMA Islam Al Ghozali secara umum menunjukkan performa yang sangat baik pada aspek karakter spiritual (82.10) dan iklim keamanan sekolah (88.40). Namun, indikator kemampuan numerasi (64.20) menjadi fokus utama perbaikan karena berada di bawah target mutu nasional.\n\nII. IDENTIFIKASI DAN REFLEKSI\n\n- Masalah Utama: Rendahnya kemampuan numerasi siswa disebabkan oleh pembelajaran matematika yang masih teoretis dan kurang kontekstual.\n- Akar Masalah: Guru belum terbiasa merancang metode pembelajaran berbasis proyek (PBL) dan kurang mengoptimalkan media digital (LMS) untuk pembelajaran eksak.\n\nIII. BENAHI & STRATEGI PEMULIHAN\n\n- Mengadakan In-House Training (IHT) perancangan modul ajar numerasi bagi guru.\n- Menerapkan teknologi digital ramah kuota untuk tryout CBT mandiri.\n- Meningkatkan peran kepala sekolah dalam melakukan supervisi klinis secara berkala.${footer}`;

    case "RKT":
      return `${header}RENCANA KERJA TAHUNAN (RKT) TAHUN 2026\n\nBerdasarkan hasil Perencanaan Berbasis Data (PBD) dengan pendekatan Identifikasi, Refleksi, dan Benahi (IRB), ditetapkan Rencana Kerja Tahunan (RKT) beserta estimasi anggarannya:\n\n[TABLE_START]\n[TABLE_ROW]Tahap IRB|Identifikasi Masalah|Program Benahi (RKT)|Rincian Kegiatan RKAS|Estimasi Anggaran\n[TABLE_ROW]Identifikasi|Capaian Numerasi Siswa masih sedang (64.20).|Peningkatan Kompetensi Numerasi Terpadu|Pengadaan Bank Soal Numerasi AKM & Program Bimbingan Pagi|Rp 12.500.000,-\n[TABLE_ROW]Refleksi|Metode pengajaran variatif berbasis teknologi belum merata.|Penguatan Pedagogi & Digitalisasi Guru|Workshop Pembelajaran Interaktif, AI, dan PBL bagi Guru|Rp 18.000.000,-\n[TABLE_ROW]Benahi|Fasilitas pendukung sarana laboratorium komputasi belum optimal.|Modernisasi Sarana Digital Pembelajaran|Upgrade Bandwidth Internet, Server LMS, & Smart Interactive Display|Rp 35.000.000,-\n[TABLE_ROW]Benahi|Supervisi akademik belum menyentuh umpan balik klinis.|Supervisi dan Pendampingan Sebaya|Pelaksanaan Coaching & Mentoring Peer-Teaching berkala|Rp 6.500.000,-\n[TABLE_END]\n\nTotal Anggaran Program Mutu RKT/RKAS 2026: Rp 72.000.000,- (Tujuh Puluh Dua Juta Rupiah) yang bersumber dari dana BOS dan Anggaran Operasional Yayasan.\n\nPelaksanaan program ini dipantau secara mingguan oleh TPMPS dan dilaporkan kepada yayasan secara transparan.${footer}`;

    case "RKJM":
      return `${header}RENCANA KERJA JANGKA MENENGAH (RKJM)\nPERIODE 2026 - 2030\n\n1. ARAH PENGEMBANGAN JANGKA MENENGAH\n\nDalam rangka mewujudkan visi sekolah: "${data.visi}", kami merancang peta jalan pengembangan sekolah berdurasi 4 tahun ke depan dengan fokus penjaminan mutu sirkuler.\n\n2. ROADMAP TAHUNAN (2026 - 2030):\n\n- Tahun I (2026) - Tahap Inisiasi & Kompetensi Pendidik:\n  Fokus pada peningkatan kompetensi literasi-numerasi guru, habituasi karakter spiritual harian siswa, dan digitalisasi dasar KBM.\n- Tahun II (2027) - Tahap Integrasi Sistem & Infrastruktur:\n  Modernisasi sarana fisik laboratorium komputasi, pengembangan LMS mandiri, dan penguatan jejaring kemitraan industri.\n- Tahun III (2028) - Tahap Evaluasi & Peningkatan Akreditasi:\n  Audit Mutu Internal (AMI) mandiri, penguatan komunitas belajar (Kombel) antar sekolah, dan persiapan akreditasi unggul.\n- Tahun IV (2029-2030) - Tahap Kemandirian & Keunggulan Global:\n  Mencapai target lulusan 100% tervalidasi, perluasan tryout masuk PTN unggulan, dan standarisasi internasional.\n\n3. ANALISIS SOAR (STRENGTHS, OPPORTUNITIES, ASPIRATION, RESULTS)\n\n- Kekuatan: Dukungan solid komite, akreditasi A, guru berkualifikasi S1/S2.\n- Peluang: Kolaborasi teknologi kecerdasan buatan, pendanaan program dari yayasan.\n- Aspirasi: Menjadi rujukan utama sekolah Islam bermutu berbasis teknologi.\n- Hasil: Lulusan kompeten, beradab, dan fasih berbahasa internasional.${footer}`;

    case "Program Perbaikan Mutu":
      return `${header}PROGRAM PERBAIKAN MUTU SEKOLAH\n(CONTINUOUS QUALITY IMPROVEMENT TAHUN 2026)\n\nProgram perbaikan mutu disusun secara terencana dengan prinsip berkesinambungan:\n\n- Program "Al-Ghozali Literacy & Numeracy Excellence": Pembiasaan 15 menit membaca literasi ilmiah Islami dan penyelesaian 2 soal numerasi HOTS setiap pagi sebelum KBM.\n- Program Digital Transformation & AI for Education: Pelatihan pembuatan bahan ajar interaktif, evaluasi otomatis, dan pemanfaatan sistem manajemen sekolah terpadu.\n- Program Tahfidz & Character Building: Pembinaan kedisiplinan, shalat berjamaah, dan integrasi adab dalam seluruh mata pelajaran.\n- Supervisi Akademik Berkelanjutan: Pelaksanaan supervisi klinis oleh Kepala Sekolah dan Tim Pengembang Kurikulum minimal 2 kali per semester untuk setiap guru.\n\nJADWAL PELAKSANAAN PROGRAM MUTU:\n\n[TABLE_START]\n[TABLE_ROW]Nama Program|Target Sasaran|Waktu Pelaksanaan|Indikator Keberhasilan\n[TABLE_ROW]Klinik Numerasi|Siswa Rapor Merah/Kuning|Mingguan (Jumat Sore)|Nilai Asesmen &ge; 75.0\n[TABLE_ROW]Workshop AI Guru|Seluruh Pendidik|Bulan Februari & Agustus|100% Guru punya Modul AI\n[TABLE_ROW]Supervisi Klinis|32 Pendidik|2x per Semester|Skor KBM Guru &ge; 85.0\n[TABLE_END]${footer}`;

    case "SOP":
      return `${header}STANDAR OPERASIONAL PROSEDUR (SOP) SPMI\n\nI. TUJUAN\nMemberikan pedoman baku bagi TPMPS dalam melaksanakan tahapan siklus PPEPP secara disiplin dan konsisten.\n\nII. PROSEDUR UTAMA SIKLUS MUTU:\n\n1. SOP Penetapan Standar:\n   - Mengkaji hasil Rapor Pendidikan dan EDS.\n   - Merumuskan draft kriteria/indikator mutu baru.\n   - Pleno persetujuan senat sekolah dan pengesahan Kepala Sekolah.\n2. SOP Pelaksanaan Standar:\n   - Sosialisasi standar mutu kepada guru, tenaga kependidikan, dan siswa.\n   - Pembagian tugas mengajar dan anggaran RKAS.\n   - Pendampingan berkala melalui komunitas belajar.\n3. SOP Evaluasi Standar:\n   - Pengisian instrumen monitoring berkala (bulanan).\n   - Audit Mutu Internal (AMI) akhir tahun oleh auditor tersertifikasi.\n4. SOP Pengendalian Standar:\n   - Identifikasi kesenjangan (gap) hasil evaluasi.\n   - Pelaksanaan Rapat Tinjauan Manajemen (RTM).\n   - Rekomendasi tindakan korektif / perbaikan.\n5. SOP Peningkatan Standar:\n   - Penaikan indikator kompetensi pada siklus berikutnya secara berkala.\n\nIII. KEPATUHAN DAN REVIU\nSetiap unit wajib melaporkan kepatuhan pelaksanaan SOP ini kepada Ketua TPMPS secara periodik.${footer}`;

    case "Monitoring":
      return `${header}LAPORAN HASIL MONITORING INTERNAL BULANAN\n\nTabel Hasil Monitoring dan Evaluasi Kinerja (Monev Caturwulan I):\n\n[TABLE_START]\n[TABLE_ROW]Aspek Evaluasi Mutu|Target Standard|Capaian Riil|Status|Catatan Evaluator\n[TABLE_ROW]Kehadiran Guru dalam KBM|98.0 %|97.5 %|Sangat Baik|Kedisiplinan sangat baik, ketidakhadiran karena tugas dinas resmi.\n[TABLE_ROW]Penggunaan LMS & Modul AI|100.0 % Guru|90.0 % Guru|Baik|3 Guru senior masih memerlukan pendampingan intensif.\n[TABLE_ROW]Rata-rata Tryout Numerasi|&ge; 72.00|68.50|Cukup|Perlu akselerasi pada modul penalaran aljabar dan data.\n[TABLE_ROW]Kepuasan Orang Tua Siswa|&gt; 85.0 %|89.2 %|Sangat Baik|Komunikasi terjalin transparan melalui laporan digital terpadu.\n[TABLE_END]\n\nKESIMPULAN MONITORING:\nSecara umum pelaksanaan program kerja berjalan lancar. Fokus perhatian bulan berikutnya adalah meningkatkan keterlibatan guru senior dalam pemanfaatan teknologi digital melalui program pendampingan sebaya (peer-mentoring).${footer}`;

    case "Evaluasi":
      return `${header}LAPORAN EVALUASI PELAKSANAAN PROGRAM MUTU\n\nI. LATAR BELAKANG EVALUASI\n\nEvaluasi tengah tahun dilaksanakan untuk mengukur tingkat efektivitas dan ketercapaian program kerja RKT yang didanai oleh anggaran RKAS. Fokus utama evaluasi adalah menilai dampak program terhadap peningkatan mutu lulusan.\n\nII. HASIL EVALUASI PROGRAM UTAMA\n\n1. Program Klinik Numerasi:\n   Mampu mendongkrak kebiasaan siswa dalam menyelesaikan soal-soal penalaran numerik berbasis HOTS. Nilai rata-rata tryout mengalami kenaikan dari 64.20 menjadi 68.50.\n2. Program Digitalisasi Bahan Ajar:\n   Telah berjalan dengan baik. Sebagian besar guru telah mengunggah rencana pembelajaran dan modul ajar mandiri pada platform LMS sekolah.\n3. Hambatan Teridentifikasi:\n   Keterbatasan konektivitas internet pada jam-jam sibuk di laboratorium komputer, serta kurangnya waktu latihan mandiri guru senior.\n\nIII. REKOMENDASI PERBAIKAN\n\n- Memperluas bandwidth internet sekolah.\n- Mengoptimalkan pendampingan sejawat oleh guru-guru muda.${footer}`;

    case "Audit Mutu Internal":
      return `${header}LAPORAN AUDIT MUTU INTERNAL (AMI)\n\nI. TIM AUDITOR DAN RUANG LINGKUP\n\nAudit Mutu Internal dilaksanakan oleh auditor internal independen yang ditunjuk oleh pimpinan sekolah, mencakup audit dokumen proses pembelajaran, pemenuhan KKM, keaktifan KBM, dan evaluasi hasil belajar siswa.\n\nII. TEMUAN AUDIT (CONFORMITY & NON-CONFORMITY)\n\n- Temuan Kepatuhan (Conformity):\n  Dokumen administrasi modul ajar, prota, dan promes 100% lengkap dan tervalidasi oleh Waka Kurikulum.\n- Temuan Ketidakpatuhan (Non-Conformity):\n  Terdapat 3 guru senior yang belum memanfaatkan fitur interaktif LMS secara optimal, masih bergantung pada pengajaran teoretis konvensional.\n\nIII. TINDAK LANJUT DAN REKOMENDASI\n\nAuditee wajib melakukan tindakan perbaikan dengan mengikuti bimbingan teknis intensif bersama tim IT Kurikulum paling lambat 14 hari setelah laporan ini diterbitkan.${footer}`;

    case "RTL":
      return `${header}DOKUMEN RENCANA TINDAK LANJUT (RTL) MUTU SEKOLAH\n\nBerdasarkan hasil monitoring, evaluasi, dan temuan audit internal, dirumuskan Matriks Rencana Tindak Lanjut (RTL) untuk perbaikan mutu yang berkelanjutan:\n\n[TABLE_START]\n[TABLE_ROW]Temuan Evaluasi|Akar Masalah|Rencana Tindak Lanjut|Penanggung Jawab|Deadline\n[TABLE_ROW]Rata-rata Tryout Numerasi belum mencapai target (68.5 vs 72.0).|Siswa kurang terbiasa dengan soal numerasi berbasis narasi panjang.|Penyusunan Modul Praktis "1 Hari 2 Soal Numerasi" & Klinik Belajar.|Tim MGMP Matematika|30 April 2026\n[TABLE_ROW]10% Guru senior belum menguasai pembuatan modul AI.|Kurangnya waktu latihan mandiri di luar jam KBM.|Program *Peer-Mentoring* 1 Guru Muda mendampingi 1 Guru Senior.|Tim IT Kurikulum|15 April 2026\n[TABLE_END]\n\nSeluruh rencana perbaikan wajib dipantau dan dikendalikan secara ketat oleh TPMPS agar tuntas sesuai deadline.${footer}`;

    case "Laporan SPMI":
      return `${header}LAPORAN PELAKSANAAN PENJAMINAN MUTU INTERNAL\n\nI. RINGKASAN KETERCAPAIAN SIKLUS PPEPP\n\n- Penetapan (P): Telah diterbitkan 10 standar operasional mutu dan SK TPMPS 2026.\n- Pelaksanaan (P): Program pelatihan AI guru dan klinik numerasi telah berjalan 100% sesuai jadwal.\n- Evaluasi (E): Laporan Monev menunjukkan indikator mutu rata-rata mencapai 85.5%.\n- Pengendalian (P): Hambatan kemampuan numerasi diintervensi melalui penambahan jam klinik belajar.\n- Peningkatan (P): Target indikator numerasi ditingkatkan dari 64.20 menjadi 75.00 pada siklus berikutnya.\n\nII. KESIMPULAN PELAKSANAAN\n\nPelaksanaan SPMI 2026 di SMA Islam Al-Ghozali berjalan efektif dan memberikan dampak nyata terhadap peningkatan kualitas pembelajaran serta tata kelola sekolah yang akuntabel dan transparan.${footer}`;

    case "Berita Acara":
      return `${header}BERITA ACARA RAPAT PLENO PENETAPAN DOKUMEN SPMI\n\nPada hari ini Senin tanggal Dua Belas bulan Januari tahun Dua Ribu Dua Puluh Enam, bertempat di Ruang Rapat SMA Islam Al-Ghozali, telah dilaksanakan Rapat Pleno Penetapan Dokumen SPMI dan Rencana Kerja Sekolah Berbasis Data Tahun 2026.\n\nRapat menghasilkan keputusan:\n1. Menerima dan mengesahkan Peta Mutu SMA Islam Al-Ghozali Tahun 2026.\n2. Menyetujui alokasi prioritas anggaran RKAS untuk penguatan Numerasi dan Digitalisasi Sekolah.\n3. Mewajibkan seluruh staf pengajar menjalankan rekomendasi Perbaikan Mutu secara konsisten.\n\nDAFTAR HADIR PERWAKILAN PLENO:\n\n[TABLE_START]\n[TABLE_ROW]No|Nama|Jabatan|Tanda Tangan\n[TABLE_ROW]1|${data.kepalaSekolah}|Kepala Sekolah|1. [Tandatangan Digital]\n[TABLE_ROW]2|Ketua Komite Sekolah|Ketua Komite|2. [Tandatangan Digital]\n[TABLE_ROW]3|${data.ketuaSPMI}|Ketua TPMPS|3. [Tandatangan Digital]\n[TABLE_ROW]4|Sekretaris SPMI|Sekretaris|4. [Tandatangan Digital]\n[TABLE_END]${footer}`;

    case "Notulen":
      return `${header}NOTULEN RAPAT PLENO PENJAMINAN MUTU\n\nHari/Tanggal: Senin, 12 Januari 2026\nWaktu       : 09.00 - 12.00 WIB\nTempat      : Ruang Rapat Utama\nPimpinan    : ${data.kepalaSekolah}\nNotulis     : Sekretaris TPMPS\n\nAGENDA RAPAT:\n1. Pemaparan hasil Rapor Pendidikan 2025.\n2. Pembahasan rencana intervensi numerasi & literasi digital.\n3. Pengesahan dokumen SPMI Volume I-VI.\n\nHASIL KEPUTUSAN:\n- Menyetujui alokasi dana RKAS sebesar Rp 72.000.000,- untuk program mutu.\n- Menetapkan program "Literacy & Numeracy Excellence" dilaksanakan setiap pagi.\n- Pembagian tugas tim pelaksana program dimulai efektif semester genap.`;

    case "Daftar Hadir":
      return `${header}DAFTAR HADIR PESERTA RAPAT PLENO MUTU\n\n[TABLE_START]\n[TABLE_ROW]No|Nama Peserta Rapat|Jabatan|Tanda Tangan\n[TABLE_ROW]1|${data.kepalaSekolah}|Kepala Sekolah|Hadir\n[TABLE_ROW]2|${data.ketuaSPMI}|Ketua TPMPS|Hadir\n[TABLE_ROW]3|Ketua Komite Sekolah|Komite|Hadir\n[TABLE_ROW]4|Koordinator Pembelajaran|PJ Standar|Hadir\n[TABLE_ROW]5|Koordinator Kurikulum|PJ Kurikulum|Hadir\n[TABLE_ROW]6|Waka Sarpras|PJ Sarpras|Hadir\n[TABLE_END]\n\nCatatan: Daftar hadir di atas tervalidasi secara sah melalui sistem administrasi digital sekolah.`;

    case "Instrumen":
      return `${header}INSTRUMEN MONITORING DAN EVALUASI KBM\n\nPetunjuk Pengisian:\nBerikan tanda centang pada kriteria penilaian di bawah ini berdasarkan hasil observasi nyata di kelas selama proses belajar mengajar.\n\nKRITERIA MONITORING KELAS:\n- Apakah pendidik menyampaikan tujuan pembelajaran secara jelas di awal KBM?\n- Apakah proses pembelajaran dirancang berpusat pada siswa (SCL)?\n- Apakah guru memanfaatkan media teknologi (LMS / slide interaktif / AI) secara optimal?\n- Apakah terdapat kuis atau asesmen formatif instan untuk mengukur pemahaman siswa?\n- Apakah guru memberikan umpan balik yang konstruktif dan memotivasi?\n\nSkor Evaluasi: 1 (Kurang), 2 (Cukup), 3 (Baik), 4 (Sangat Baik).${footer}`;

    case "Checklist":
      return `${header}CHECKLIST KELENGKAPAN LAYANAN SPMI\n\nChecklist kelengkapan berkas fisik akreditasi dan dokumen penjaminan mutu internal:\n\n- [v] Buku I: Dokumen Kebijakan Mutu SPMI\n- [v] Buku II: Dokumen Manual & Prosedur Mutu\n- [v] Buku III: Dokumen Standar Mutu Lulusan (SKL)\n- [v] Buku IV: Dokumen Formulir & Borang Penilaian\n- [v] Surat Keputusan Penetapan TPMPS 2026\n- [v] Laporan Evaluasi Diri Sekolah (EDS)\n- [v] Peta Mutu Sekolah berbasis data Rapor Pendidikan\n- [v] Laporan Rencana Kerja Tahunan (RKT) & RKAS\n- [ ] Laporan Hasil Audit Mutu Internal (AMI) Tengah Tahun\n- [v] Laporan RTL Mutu dan Rekomendasi Tindak Lanjut\n- [v] Berita Acara & Daftar Hadir Pleno Mutu`;

    case "Bukti Fisik":
      return `${header}REKAPITULASI DOKUMENTASI KEGIATAN & BUKTI FISIK\n\nUntuk mempermudah proses akreditasi dan verifikasi eksternal oleh pengawas dinas, berikut rekapitulasi bukti fisik pelaksanaan SPMI:\n\n[TABLE_START]\n[TABLE_ROW]Tanggal|Kegiatan|Bentuk Arsip Dokumentasi|Status Simpan\n[TABLE_ROW]12 Jan 2026|Rapat Pleno SPMI & Penetapan PBD|Foto Rapat, Daftar Hadir, File PDF PBD|Google Drive SPMI / Folder 01\n[TABLE_ROW]05 Feb 2026|Workshop AI & Pedagogi Digital Guru|Foto Workshop, Modul Pelatihan, Video Rekaman|Google Drive SPMI / Folder 02\n[TABLE_ROW]18 Mar 2026|Supervisi Klinis KBM & Monev Caturwulan I|Instrumen Terisi, Foto Evaluasi, Rekaman Kelas|Google Drive SPMI / Folder 03\n[TABLE_END]\n\nCatatan Penyimpanan: Seluruh berkas digital, foto resolusi tinggi, dan video rekaman KBM telah diarsipkan pada Cloud Storage Resmi Sekolah dengan tautan akses internal TPMPS.`;

    default:
      return `${header}Template not found for id: ${templateId}`;
  }
}

export async function generateDocumentContent(
  templateId: string,
  data: SPMIData
): Promise<string> {
  try {
    const response = await fetch('/api/generate-document', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ templateId, data }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        console.warn('Gemini API quota exceeded (429). Falling back to professional offline document generation.');
        return generateLocalDocumentContent(templateId, data);
      }
      throw new Error('Failed to generate document content');
    }

    const { content } = await response.json();
    return content;
  } catch (error) {
    console.warn('API call failed, generating highly detailed offline document content instead:', error);
    return generateLocalDocumentContent(templateId, data);
  }
}
